name: flutter_fortune_wheel
description: Visualize (random) selection processes with widgets like a spinning wheel of fortune or a fortune bar.
repository: https://github.com/kevlatus/flutter_fortune_wheel
version: 0.2.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.15.0
  quiver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
