name: flutter_fortune_wheel
description: Customizable widgets for visualizing random selections.
repository: https://github.com/kevlatus/flutter_fortune_wheel
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.15.0
  quiver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
