name: flutter_fortune_wheel
description: Visualize (random) selection processes with widgets like a spinning wheel of fortune or a fortune bar.
repository: https://github.com/kevlatus/flutter_fortune_wheel
version: 1.3.2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.2
